Fix incompatible pointers arguments
The wrapped_obj_len variable on 32b architecture is of a different size
than expected by the PKCS #11 API, causing build failures.

In file included from /builddir/build/BUILD/yubihsm-shell-2.6.0-build/yubihsm-shell-2.6.0/pkcs11/tests/asym_wrap_test.c:20:
/builddir/build/BUILD/yubihsm-shell-2.6.0-build/yubihsm-shell-2.6.0/pkcs11/tests/asym_wrap_test.c: In function ‘get_wrapped_data’:
/builddir/build/BUILD/yubihsm-shell-2.6.0-build/yubihsm-shell-2.6.0/pkcs11/tests/asym_wrap_test.c:344:25: error: passing argument 6 of ‘p11->C_WrapKey’ from incompatible pointer type [-Wincompatible-pointer-types]
  344 |                         wrapped_obj_len) == CKR_OK);
      |                         ^~~~~~~~~~~~~~~
      |                         |
      |                         size_t * {aka unsigned int *}
/builddir/build/BUILD/yubihsm-shell-2.6.0-build/yubihsm-shell-2.6.0/pkcs11/tests/asym_wrap_test.c:344:25: note: expected ‘CK_ULONG_PTR’ {aka ‘long unsigned int *’} but argument is of type ‘size_t *’ {aka ‘unsigned int *’}
/builddir/build/BUILD/yubihsm-shell-2.6.0-build/yubihsm-shell-2.6.0/pkcs11/tests/asym_wrap_test.c:344:25: error: passing argument 6 of ‘p11->C_WrapKey’ from incompatible pointer type [-Wincompatible-pointer-types]
  344 |                         wrapped_obj_len) == CKR_OK);
      |                         ^~~~~~~~~~~~~~~
      |                         |
      |                         size_t * {aka unsigned int *}
/builddir/build/BUILD/yubihsm-shell-2.6.0-build/yubihsm-shell-2.6.0/pkcs11/tests/asym_wrap_test.c:344:25: note: expected ‘CK_ULONG_PTR’ {aka ‘long unsigned int *’} but argument is of type ‘size_t *’ {aka ‘unsigned int *’}

Signed-off-by: Jakub Jelen <jjelen@redhat.com>