misc: do not set -pie on shared libraries
"Position independent executables" is only really applicable for...
executables. In fact, it may not even build when this flag is set on
shared libraries

	[2/41] Linking C shared library ykhsmauth/libykhsmauth.so.2.7.0
	<snip>
	(.text+0x1b): undefined reference to `main'
	collect2: error: ld returned 1 exit status