Support PKCS11 3.0 (#183)
* Use PKCS11 3.0 headers

* Added files to be installed

* Basic PKCS11 3.0 support

* Make function lists static

* Make function lists const

* Refactored C_Login and C_LoginUser

* Rebase fixes

* Rebase changes

* Support ed25519

* Fix attributes for ed25519 keys

* ed25519 keys are considered 255 bits. Refactor getting CKA_EC_POINT slightly

* pkc11 3.1

* fix buffer_length check for EdDSA in util_pkcs11.c (#390)

Having problems signing with EdDSA on YubiHSM2 via PKCS11.
Getting an 
pkcs11:p11prov_Sign:The size of plaintext input data to a cryptographic operation is invalid (Out of range):interface.gen.c:679:Error returned by C_Sign
error

As I understand the PKCS11 v3.0 spec, the 1024 bit limit (note by "adma" in line 2228) applies only to "ECDSA without hashing" (CKM_ECDSA) as it only processes a hash value.

see: https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc30061189

EdDSA does not have this limit, so the size of "op_info->buffer" should be the limiting factor

see: https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc30061191

* PKCS11: Rebase on current master

* PKCS11: Fix include for older OSs. Githubactions: Fix OpenSSL installation on MacOS runners

* PKCS11: Compile ED25519 code only when OpenSSL is higher than 1.0. Build: Fix Redhat and MacOS builds

* PKCS11: Fix header inclusion in test

* PKCS11: Update tests to use PKCS11_3 functionlist. Add test for PKCS11 interfaces

* PKCS11: Remove unnecessary KDF definitions

* PKCS11: Fix PKCS11 interfaces test

* PKCS11_3: return CKR_PIN_INCORRECT when logging in with wrong password

* Only C_GetInfo from 3.x function list returns 3.x cryptoki version

* PKCS11_3: Use snprintf instead of sprintf

* PKCS11_3: Fix allocation of arrays

* More usage of snprintf

---------

Co-authored-by: marcwillert <78364219+marcwillert@users.noreply.github.com>
Co-authored-by: Aveen Ismail <aveen.ismail@yubico.com>